//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    pub part_id: i64,
    pub location_id: i64,
    pub owner_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub legal_entity: HasOne<super::legal_entity::Entity>,
    #[sea_orm(
        belongs_to,
        from = "location_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub location: HasOne<super::location::Entity>,
    #[sea_orm(
        belongs_to,
        from = "part_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub part: HasOne<super::part::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
