//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "part")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub parent_part_id: Option<i64>,
    pub category_id: Option<i64>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub label_text: Option<String>,
    pub concrete: bool,
    pub image: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub category: HasOne<super::category::Entity>,
    #[sea_orm(has_many)]
    pub items: HasMany<super::item::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_part_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub part: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub part_parameter_definitions: HasMany<super::part_parameter_definition::Entity>,
    #[sea_orm(has_many)]
    pub part_parameter_values: HasMany<super::part_parameter_value::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
