//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "part_parameter_definition")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parameter_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub part_id: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub default_value_real: Option<f64>,
    pub default_value_string: Option<String>,
    pub default_value_int: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "parameter_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub parameter: HasOne<super::parameter::Entity>,
    #[sea_orm(
        belongs_to,
        from = "part_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub part: HasOne<super::part::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
