//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "legal_entity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub owner_id: Option<i64>,
    pub name: String,
    pub url: Option<String>,
    pub supplier: bool,
    pub manufacturer: bool,
    pub customer: bool,
    pub owner: bool,
    #[sea_orm(has_many)]
    pub items: HasMany<super::item::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub legal_entity: HasOne<Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
