//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod category;
pub mod item;
pub mod legal_entity;
pub mod location;
pub mod parameter;
pub mod part;
pub mod part_parameter_definition;
pub mod part_parameter_value;
