//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "location")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub parent_location_id: Option<i64>,
    pub name: String,
    pub description: Option<String>,
    pub label_text: Option<String>,
    #[sea_orm(has_many)]
    pub items: HasMany<super::item::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_location_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub location: HasOne<Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
