//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "parameter")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub r#type: i64,
    pub symbol: Option<String>,
    pub unit: Option<String>,
    #[sea_orm(has_many)]
    pub part_parameter_definitions: HasMany<super::part_parameter_definition::Entity>,
    #[sea_orm(has_many)]
    pub part_parameter_values: HasMany<super::part_parameter_value::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
